### ISSUE TITLE
config example is missing values from config default file

### ISSUE THREAD

**Issue by rubo77** [hopglass/hopglass-server#105]
There are some values in `config.json.defaults` that are not in the `config.json.example`: 

- receivers->config target and port
- receivers->overlay
- storage interval
- purge interval

Is it ok? Or what happens if those values are missing?
If you cann ommit the values, it should be explained in the README or as comments in the config file.

**Comment by petabyteboy** [comment]
I think it is self-explanatory. The values in config.json.defaults provide *default* values, which are used if nothing else is specified. config.json.defaults should give an overview of all available options. config.json.example is an example configuration like it might be used in production. You can even run hopglass server without a config file and it will use all the default values.
