### ISSUE TITLE
dangerous apt remove in bootstrap

### ISSUE THREAD

**Issue by rubo77** [hopglass/hopglass-server#110]
I just used the bootstrap.sh on Debian 10 (buster), and go t some problems: 

1. `pidof systemd` does not return anything, so it sais, systemd is not installed
2. in the process, there is the command `apt-get remove nodejs nodejs-legacy npm` which results in also removing important still needed packages:

```
Die folgenden Pakete werden ENTFERNT:                               
  jekyll node-* nodejs npm ruby-coffee* ruby-execjs ruby-jekyll-coffeescript ruby-turbolinks ruby-uglifier
```
This wouln't be good, if you continue with Yes, since those packages are important on my system.

How can we prevent this? maybe add `--no-recommends` ? I asked [here](https://unix.stackexchange.com/questions/553300/apt-remove-a-package-but-keep-co-installed-packages) and [here](https://unix.stackexchange.com/questions/553297/how-do-i-correctly-check-if-the-system-uses-systemd)

**Comment by rubo77** [comment]
I tried this:

    sudo apt-mark manual  jekyll ruby-jekyll-coffeescript ruby-turbolinks ruby-uglifier

but no effect:

```

jekyll wurde bereits auf manuell installiert gesetzt.
ruby-jekyll-coffeescript wurde bereits auf manuell installiert gesetzt.

**Comment by rubo77** [comment]
maybe use dpkg -r instead:

    dpkg -r  nodejs nodejs-legacy npm

**Comment by petabyteboy** [comment]
This is completely obsolete anyways. Recent versions of Debian or Ubuntu should ship a NodeJS version which is recent enough to run hopglass server. I will link to the installation instructions on the NodeJS website.
