### ISSUE TITLE
 config file "undefined" doesn't exist, using defaults

### ISSUE THREAD

**Issue by rubo77** [hopglass/hopglass-server#112]
When I restart with 
  
    service hopglass-server@default restart

`journalctl -u hopglass-server@default ` shows:

```
: Stopping The HopGlass Server collects data from the Freifunk network (default)...
: hopglass-server@default.service: Succeeded.
: Stopped The HopGlass Server collects data from the Freifunk network (default).
: Started The HopGlass Server collects data from the Freifunk network (default).
 config file "undefined" doesn't exist, using defaults
 alias file "./aliases.json" doesn't exist, using empty
 collector listening on port 45123
 webserver listening on port 4000
```
although the file `config.json` exists and belongs to the user `hopglass`. maybe because I created a symlink

```
# ll /etc/hopglass-server/default/config.json
lrwxrwxrwx 1 root root 32 Nov 21 06:48 /etc/hopglass-server/default/config.json -> /opt/hopglass/server/config.json
```
even if I copy our config.json to config.json.example, I get the same error.

Now our nodes.json is empty, because the config file isn't used:

https://hopglass.freifunk.in-kiel.de/nodes.json

**Comment by rubo77** [comment]
Any Idea, how I can fix our server? 🤔

**Comment by petabyteboy** [comment]
Try placing your config file in /var/lib/hopglass-server/config.json. I will have to think about the best way to do this, since the default data and config storage paths are in the working directory of the process.

**Comment by rubo77** [comment]
placing symlinks worked:

```
# ll /var/lib/hopglass-server
lrwxrwxrwx 1 root root 23 Nov 21 10:57 /var/lib/hopglass-server -> private/hopglass-server
root@freifunk:/var/lib/hopglass-server# ll /var/lib/hopglass-server/
insgesamt 4
lrwxrwxrwx 1 root  root  41 Nov 21 18:59 aliases.json -> /etc/hopglass-server/default/aliases.json
lrwxrwxrwx 1 root  root  40 Nov 21 18:58 config.json -> /etc/hopglass-server/default/config.json
-rw-r--r-- 1 64659 64659  2 Nov 21 18:57 raw.json
```
I wonder what the 2byte raw.json file there is doing, and why it has such a strange owner-ID. It seems not to be used at all

**Comment by petabyteboy** [comment]
No, that's fine. The user id is automatically assigned by systemd, because I have set DynamicUser to true.
