### ISSUE TITLE
gateway info missing from prometheus data

### ISSUE THREAD

**Issue by RalfJung** [hopglass/hopglass-server#116]
According to https://github.com/hopglass/hopglass-server#metrics-values, the per-node stats should all come with the labels hostname, nodeid and gateway. However, that does not seem to be the case any more: the entries in statistics_clients_total look like this:
```
statistics_clients_total{hostname="ffsaar-caravanplatz-uplink",instance="localhost:4000",job="hopglass",model="Ubiquiti  Rocket M2",nodeid="687251664883",site="ffsaar"} | 11
statistics_clients_total{hostname="Bühlstraße-Test_Wadrilltal_ffsaar",instance="localhost:4000",job="hopglass",model="GL-MT300N-V2",nodeid="e4956e43fdbc",site="ffsaar"} | 1
```
There's no "gateway" info. We used to have this info, but at some point it must have stopped working.

**Comment by petabyteboy** [comment]
This was removed in https://github.com/hopglass/hopglass-server/pull/82. If you want, create a PR to remove the outdated part from the docs.
