### ISSUE TITLE
feature idea: freifunk api support

### ISSUE THREAD

**Issue by mar-v-in** [hopglass/hopglass-server#35]
Would be awesome if we could add a possibility to provide a Freifunk API file through hopglass-server. A request to `/api/xxx.json` could return a provided api file from `./api/xxx.json` (custom path possible of course) with nodes count for site xxx and lastchange populated. This way the API file is automatically kept up-to-date - and when being there you can even add json schema validation for the API file, to ensure people don't mess things up :)

**Comment by plumpudding** [comment]
Done in master. I will add validation later.

**Comment by mar-v-in** [comment]
Nice, I will try this out as soon as possible.
Unfortunately we did not deplay sites at ffsaar yet, still work in progress ;)

**Comment by plumpudding** [comment]
I will close this. Testing for API validity is out of the scope of this project.
