### ISSUE TITLE
Inconsistent online counts

### ISSUE THREAD

**Issue by tantive** [hopglass/hopglass-server#47]
The number of online nodes is reported inconsistently (973 vs. 994):
http://map.freifunk-stuttgart.de/

1102 Knoten (973 online, 576 neu, 134 verschwunden), 2709 Clients, 9 Gateways

Status 
   online	994
   offline	113

Any ideas? Where and how are the two values computed?

**Comment by plumpudding** [comment]
They are both the sum of the client counts of online nodes. The difference is the method used to determine whether a node is online.

**Comment by plumpudding** [comment]
At the time of this writing the difference is the same as the amount of gateways. I will close this issue, as I can see it working in other communities (https://map.ffdus.de) and your community seems to be using a modified version of HopGlass. Anyways this is the wrong repository.
