### ISSUE TITLE
ffapi.json empty

### ISSUE THREAD

**Issue by sap-dev** [hopglass/hopglass-server#48]
Our ffapi.json File is empty. 
Can you tell us, how we become an nodelist.json or we can include hopglass data to the FFNet Api File?

**Comment by plumpudding** [comment]
There are 2 possibilities:
1) You serve your api file yourself. You will have to include something like this:
```
  "nodeMaps": [
    {
      "url": "https://lln.map.ffgl.eu/data/nodelist.json",
      "technicalType": "nodelist"
    }
  ],
```

2) You let the HopGlass Server serve your api file. Place your api file (including the above section) in /etc/hopglass-server/default/ffapi/all.json. 
This has the advantage, that the HopGlass Server will update the number of nodes when delivering the file. It won't serve the file if it isn't proper json.
