### ISSUE TITLE
Provide some mock data for testing purposes

### ISSUE THREAD

**Issue by yayachiken** [hopglass/hopglass-server#68]
Because development of hopglass and hopglass-server is relatively tightly coupled, it would be useful to have an easy way to set up a testing instance of a current hopglass-server without actually starting any data collection on a Freifunk node farm.

For that reason it would be nice if hopglass-server had a way to serve a (small, static) set of mock data.

Alternatively: Provide a web service with any data that always runs the newest hopglass-server version.

**Comment by plumpudding** [comment]
Use any of these:
https://map-altena.freifunk-mk.de/data/
https://map-hemer.freifunk-mk.de/data/
https://map.freifunk-iserlohn.de/data/
https://map-luedenscheid.freifunk-mk.de/data/
https://mk.map.eulenfunk.de/data/
https://map-meinerzhagen.freifunk-mk.de/data/
https://map-neuenrade.freifunk-mk.de/data/
https://bgl.map.ffgl.eu/data/
https://lln.map.ffgl.eu/data/
https://bcd.map.ffgl.eu/data/
https://ode.map.ffgl.eu/data/
https://han.karte.neanderfunk.de/data/
https://hlg.karte.neanderfunk.de/data/
https://hld.karte.neanderfunk.de/data/
https://lgf.karte.neanderfunk.de/data/
https://met.karte.neanderfunk.de/data/
https://mon.karte.neanderfunk.de/data/
https://erk.karte.neanderfunk.de/data/
https://rat.karte.neanderfunk.de/data/
https://vel.karte.neanderfunk.de/data/
https://wlf.karte.neanderfunk.de/data/
https://freudenberg.map.eulenfunk.de/data/
https://hilchenbach.map.eulenfunk.de/data/
https://siegen.map.eulenfunk.de/data/
https://karte.ffdus.de/data/
https://gek.map.eulenfunk.de/data/
https://map.gl.wupper.ffrl.de/data/
https://wup.map.eulenfunk.de/data/
https://rade.map.eulenfunk.de/data/
