### ISSUE TITLE
add a simple webserver

### ISSUE THREAD

**Issue by rubo77** [hopglass/hopglass-server#70]
If I install this like described in the README there is no nodes.json reacheable from outside the server.

I can call it on the console with:

    curl 'http://127.0.0.1:4000/nodes.json' 

So please add a simple minimal install instructions how to get the nodes.json out of the server.

**Comment by plumpudding** [comment]
Are you running a firewall or something? HopGlass Server opens a web server serving the nodes.json on port 4000. Maybe your listening address isn't correct?

**Comment by rubo77** [comment]
Ok
