### ISSUE TITLE
implementation of site filter in hopglass

### ISSUE THREAD

**Issue by freifunk-bamberg** [hopglass/hopglass-server#72]
Hi, 
we have an sitecode filter in hopglass-server, can i implement that in the frontend?

i have tested the follow:

add variable "sitecode" to the config.json

in app.js
for(var h in a.dataPath)c.push(a.dataPath[h]+"nodes.json"),c.push(a.dataPath[h]+"graph.json");
i have modified to that:
for(var h in a.dataPath)c.push(a.dataPath[h]+"nodes.json?filter=site&value="+a.sitecode),c.push(a.dataPath[h]+"graph.json?filter=site&value="+a.sitecode);

but then the statistics page gateway used by nodes not shown right.

can you help me fix this problem?

sorry for my bad english
Thanks

**Comment by plumpudding** [comment]
site code filter is already in the frontend under statistics
we just have to get these statistics filter into the url params to be able to link them
