### ISSUE TITLE
Export Node in extra file

### ISSUE THREAD

**Issue by sap-dev** [hopglass/hopglass-server#75]
Hallo,

ich bin gerade dabei, mir die Provider ein wenig anzupassen.
Ich möchte nun folgendes erreichen: Unsere nodes.json werden viel zu groß und wir möchten diese in einzelne Dateien ablegen. Für jeden Node soll eine .json Datei auf dem Webserver des Hopglass bereitgestellt werden.

Das Format der Provider ist mir bekannt, jedoch hapert es bei der Ausgabe der Datei. Welche Ansätze gibt es hier?

**Comment by rubo77** [comment]
Benutze doch `jq` um die Datei n mehrere json dateien zu zerlegen

**Comment by plumpudding** [comment]
Das sollte auf jeden Fall hier diskutiert werden. Ich gucke es mir an.

**Comment by sap-dev** [comment]
Gute Idee!
Ich weiß nur leider nicht wie ich den Provider so gebaut bekomme. Kannst du mir hier helfen?

**Comment by plumpudding** [comment]
Für Lösung 2)
Du gehst hier hin: https://github.com/hopglass/hopglass-server/blob/master/modules/receiver.js#L124
Da fügst du einen case für filter typ "nodeid" hinzu, der nur dementsprechende Knoten zurückliefert.

**Comment by sap-dev** [comment]
Okay; und wie wird dann die URL aufgerufen?

**Comment by plumpudding** [comment]
https://lln.map.ffgl.eu/data/nodes.json?filter=nodeid&value=f4f26d42ed59
