### ISSUE TITLE
email obfuscation in nodes.json

### ISSUE THREAD

**Issue by rubo77** [hopglass/hopglass-server#80]
I would like to replace all occurrences of @ with `-at-` in the nodes.json file, before it is served.

WHere would I have to search for the code part, that is serving the nodes.json?

**Comment by anoymouserver** [comment]
The nodeinfo part is not changed for the nodes.json, so you have to do it before writing it out..

For the HopGlass you could implement it [here](https://github.com/hopglass/hopglass-server/blob/master/modules/provider/hopglass.js#L54).
For the Meshviewer you could implement it [here](https://github.com/hopglass/hopglass-server/blob/master/modules/provider/meshviewer.js#L51).
