### ISSUE TITLE
nodes.zone serial out of range

### ISSUE THREAD

**Issue by herrbett** [hopglass/hopglass-server#83]
Bind9 won't load the zone if the serial is longer then 10 digits.

I solved this issue by using seconds instead of milliseconds.

```
var seconds = Math.round(new Date().getTime()/1000)

…

stream.write(' ' + seconds + ' ; serial number\n')
```

As I never did anything in node js until this evening, there is probably a better way of solving this issue. :)

**Comment by rubo77** [comment]
Using Milliseconds and round them to a hundreds

**Comment by anoymouserver** [comment]
I would use `stream.write(' ' + Math.round(Date.now() / 1000) + ' ; serial number\n')` (like suggested).

@rubo77 .. or how would you solve it?
