### ISSUE TITLE
bind announced only to specified interface

### ISSUE THREAD

**Issue by wrosenauer** [hopglass/hopglass-server#90]
We are hosting multiple communities on the same infrastructure. E.g. multiple netmons, multiple fastds etc.
Therefore I'm trying to deploy hopglass-server in the same way and given the systemd layout with @ services I assumed this would work already.
Apparently the collector port 45123 is bound globally though instead of just per configured iface which prevents multiple hopglass-server instances from starting.

**Comment by plumpudding** [comment]
The collector port is configurable. You can simply use a different collector port for every instance. We run over 25 instances of the HopGlass server on the eulenmap.

**Comment by wrosenauer** [comment]
nice, there is no example in the config how to do it though. Can you please paste one?

**Comment by plumpudding** [comment]
https://github.com/hopglass/hopglass-server/blob/master/config.json.defaults <- this is the file with all defaults


```
{
  "receiver": {
    "receivers": [
      { "module": "announced",
        "config": {
          "target": {
            "ip": "ff02::1",
            "port": 1001
          },
          "port": 45123, // <- change port here
...
```

**Comment by wrosenauer** [comment]
In any case, wouldn't it an improvement to bind only to the corresponding iface or do I misunderstand the functionality of that network port?

**Comment by plumpudding** [comment]
that would probably be a good idea, yes
I'm looking into it

**Comment by Sunz3r** [comment]
nodejs doesn't support SO_BINDTODEVICE and need root permissions.

**Comment by plumpudding** [comment]
thanks for the info @Sunz3r
