### ISSUE TITLE
docker container

### ISSUE THREAD

**Issue by rubo77** [hopglass/hopglass-server#93]
We already have another nodeJS instance on our server, that needs v0.10.29 to run

I think the only solution to install different apps that use different nodejs versions on the same server would be docker.

Could you provide a docker install instruction, to insstall hopglass-server with the needed dependencies in a doker container?

**Comment by rotanid** [comment]
0.10.29 ? you should better remove this or run THAT in docker, as that version has security issues which won't be fixed anymore. end-of-life!
see https://github.com/nodejs/LTS

**Comment by plumpudding** [comment]
You can use nodenv or simply extract the binary package to some location and run nodejs with the absolute path. No need for a container though you probably don't want to run nodes on important systems like the supernode at all.

**Comment by petabyteboy** [comment]
hopglass-server works nicely with newer NodeJS versions, there is no need to install an old NodeJS version.
We should focus on providing packaged versions for popular distributions instead.
